#!/bin/bash
source "$(dirname "$0")/lib/common.sh"
log_info "creating default domoaudio-client configuration"
CONF="/etc/default/domoaudio-client"
if [ -f "${CONF}" ]; then
  log_info "domoaudio-client config already exists at ${CONF}"
  exit 0
fi
OUTPUT_DEV="$("$(dirname "$0")/detect-alsa-output.sh" 2>/dev/null || echo "default")"
BUFFER_MS="${DOMO_AUDIO_CLIENT_BUFFER_MS:-300}"
mkdir -p "$(dirname "${CONF}")"
{
  echo "# DomoAudio Client configuration - auto-generated by wyoming-enhancements"
  echo "DOMO_AUDIO_CLIENT_OPTS=\"--player alsa --soundcard ${OUTPUT_DEV} --buffer_ms ${BUFFER_MS}\""
  echo "START_DOMO_AUDIO_CLIENT=true"
} > "${CONF}"
log_info "domoaudio-client config created at ${CONF}: device=${OUTPUT_DEV} buffer=${BUFFER_MS}"
